### ISSUE TITLE
Basic Information about this project.

### ISSUE THREAD

**Issue by PacteraOliver** [liliangqi/person_search#3]
Hi,

I have a few questions about this project.

1. Where is the README and the instructions about how to run the code?

2. What is your Model and any paper reference?

Thank you!

**Comment by liliangqi** [comment]
Hi, I'm sorry that this project is not completely open right now due to some reasons.

**Comment by ShuoYe2020** [comment]
@liliangqi ,Thank you for sharing your code,I want to do some work on person search during this time,could you publish a little more complete code now?
